--SEQUENCIAS

CREATE SEQUENCE SQ_BRANCH INCREMENT BY 1 START WITH 1;

CREATE SEQUENCE SQ_CATEGORY INCREMENT BY 1 START WITH 1;

CREATE SEQUENCE SQ_DISPATCH_BY_WAREHOUSE INCREMENT BY 1 START WITH 1;

CREATE SEQUENCE SQ_DISPATCH_DETAILS INCREMENT BY 1 START WITH 1;

CREATE SEQUENCE SQ_N_ORDER INCREMENT BY 1 START WITH 1;
	
CREATE SEQUENCE SQ_ORDER_DETAIL INCREMENT BY 1 START WITH 1;

CREATE SEQUENCE SQ_PRODUCT INCREMENT BY 1 START WITH 1;

CREATE SEQUENCE SQ_PROVIDER INCREMENT BY 1 START WITH 1;

CREATE SEQUENCE SQ_PROVIDER_BY_PRODUCT INCREMENT BY 1 START WITH 1;
	
CREATE SEQUENCE SQ_WAREHOUSE_USER INCREMENT BY 1 START WITH 1;

--TABLAS

CREATE TABLE BITACORA (
    ID_USER      INTEGER NOT NULL,
    TRANSACTION  VARCHAR2(250) NOT NULL,
    TABLE_NAME   VARCHAR2(50) NOT NULL,
    DESCRIPTION  VARCHAR2(250),
    DATE_TIME    DATE NOT NULL
);

CREATE TABLE WAREHOUSE_USER (
    ID_USER     INTEGER NOT NULL PRIMARY KEY,
    NAME_USER   VARCHAR2(220) NOT NULL,
    PHONE_USER  VARCHAR2(11),
    JOB_TITLE   VARCHAR2(220)
);

CREATE TABLE BRANCH ( 
    ID_BRANCH       INTEGER NOT NULL PRIMARY KEY,
    NAME_BRANCH     VARCHAR2(120) NOT NULL,
    ADDRESS_BRANCH  VARCHAR2(220) NOT NULL,
    PHONE_BRANCH    VARCHAR2(11) NOT NULL
);

CREATE TABLE CATEGORY (
    ID_CATEGORY  INTEGER NOT NULL PRIMARY KEY,
    NAME         VARCHAR2(50),
    DESCRIPTION  VARCHAR2(100) 
);

CREATE TABLE N_ORDER (
    ID_ORDER      INTEGER NOT NULL PRIMARY KEY,
    DATE_TIME     DATE NOT NULL,
    TOTAL_AMOUNT  NUMBER(10, 2) NOT NULL
);

CREATE TABLE PRODUCT (
    ID_PRODUCT       INTEGER NOT NULL PRIMARY KEY,
    NAME_PRODUCT     VARCHAR2(120) NOT NULL,
    CREATED_PRODUCT  DATE NOT NULL,
    ID_CATEGORY INTEGER NOT NULL,
    CONSTRAINT PRODUCT_CATEGORY_FK FOREIGN KEY (ID_CATEGORY) REFERENCES   CATEGORY(ID_CATEGORY)
);


CREATE TABLE PROVIDER (
    ID_PROVIDER       INTEGER NOT NULL PRIMARY KEY,
    NAME_PROVIDER     VARCHAR2(250) NOT NULL,
    NIT_PROVIDER      VARCHAR2(15),
    PHONE_PROVIDER    VARCHAR2(11),
    ADDRESS_PROVIDER  VARCHAR2(220)
);


CREATE TABLE PROVIDER_BY_PRODUCT (
    ID_PROVIDER_BY_PRODUCT  INTEGER NOT NULL PRIMARY KEY,
    LAST_ADDED              DATE NOT NULL,
    ID_PROVIDER             INTEGER NOT NULL,
    ID_PRODUCT              INTEGER NOT NULL,
    ID_USER                 INTEGER NOT NULL,
    QUANTITY                INTEGER NOT NULL,
    PRICE_PRODUCT           FLOAT(10) NOT NULL,
    CONSTRAINT PROVIDER_DETAIL_FK FOREIGN KEY (ID_PROVIDER) REFERENCES   PROVIDER(ID_PROVIDER),
    CONSTRAINT PRODUCT_DETAIL_FK FOREIGN KEY (ID_PRODUCT) REFERENCES   PRODUCT(ID_PRODUCT),
    CONSTRAINT USER_DETAIL_FK FOREIGN KEY (ID_USER) REFERENCES   WAREHOUSE_USER(ID_USER)
);


CREATE TABLE ORDER_DETAIL (
    ID_DETAIL               INTEGER NOT NULL PRIMARY KEY,
    ID_PROVIDER_BY_PRODUCT  INTEGER NOT NULL,
    QUATITY_IN              INTEGER NOT NULL,
    PRICE_BY_PRODUCT        NUMBER NOT NULL,
    TOTAL_ORDER             NUMBER(10, 2) NOT NULL,
    ID_ORDER                INTEGER NOT NULL,
    CONSTRAINT PROV_PROD_DETAIL_FK FOREIGN KEY (ID_PROVIDER_BY_PRODUCT) REFERENCES   PROVIDER_BY_PRODUCT(ID_PROVIDER_BY_PRODUCT),
        CONSTRAINT ORDER_FK FOREIGN KEY (ID_ORDER) REFERENCES   N_ORDER(ID_ORDER)
);

CREATE TABLE DISPATCH_BY_WAREHOUSE (
    ID_DISPATCH_BY_WAREHOUSE  INTEGER NOT NULL PRIMARY KEY,
    ID_BRANCH                 INTEGER NOT NULL,
    ID_USER                   INTEGER NOT NULL,
    LAST_SENT                 DATE NOT NULL,
        CONSTRAINT BRANCH_DISPATCH_FK FOREIGN KEY (ID_BRANCH) REFERENCES   BRANCH(ID_BRANCH),
            CONSTRAINT USER_DISPATCH_FK FOREIGN KEY (ID_USER) REFERENCES   WAREHOUSE_USER(ID_USER)
);


CREATE TABLE DISPATCH_DETAILS (
    ID_DISPATCH               INTEGER NOT NULL PRIMARY KEY,
    ID_DISPATCH_BY_WAREHOUSE  INTEGER NOT NULL,
    QUANTITY_OUT              INTEGER NOT NULL,
    ID_PROVIDER_BY_PRODUCT    INTEGER NOT NULL,
    CONSTRAINT PROV_PROD1_DETAIL_FK FOREIGN KEY (ID_PROVIDER_BY_PRODUCT) REFERENCES   PROVIDER_BY_PRODUCT(ID_PROVIDER_BY_PRODUCT),
    CONSTRAINT DISPATCH1_DETAIL_FK FOREIGN KEY (ID_DISPATCH_BY_WAREHOUSE) REFERENCES   DISPATCH_BY_WAREHOUSE(ID_DISPATCH_BY_WAREHOUSE)
);

-----

--PROCEDIMIENTOS CRUD BRANCH
--CREATE
CREATE OR REPLACE PROCEDURE CREATE_BRANCH (PNAME_BRANCH IN BRANCH.NAME_BRANCH%TYPE,PADDRESS_BRANCH IN BRANCH.ADDRESS_BRANCH%TYPE,PPHONE_BRANCH IN BRANCH.PHONE_BRANCH%TYPE) AS
BEGIN
  INSERT INTO BRANCH (ID_BRANCH,NAME_BRANCH,ADDRESS_BRANCH,PHONE_BRANCH) VALUES (SQ_BRANCH.NEXTVAL,PNAME_BRANCH,PADDRESS_BRANCH,PPHONE_BRANCH);
  COMMIT;
END;

CALL CREATE_BRANCH ('JIFFY','MIXCO','4754-5847');


CREATE OR REPLACE PROCEDURE UPDATE_BRANCH (PID_BRANCH IN BRANCH.ID_BRANCH%TYPE, PNAME_BRANCH IN BRANCH.NAME_BRANCH%TYPE,PADDRESS_BRANCH IN BRANCH.ADDRESS_BRANCH%TYPE,PPHONE_BRANCH IN BRANCH.PHONE_BRANCH%TYPE) AS
BEGIN
  UPDATE BRANCH
  SET 
  NAME_BRANCH = PNAME_BRANCH, ADDRESS_BRANCH = PADDRESS_BRANCH , PHONE_BRANCH = PPHONE_BRANCH
  WHERE
  ID_BRANCH = PID_BRANCH;
  COMMIT;
END;

CREATE OR REPLACE PROCEDURE DELETE_BRANCH (PID_BRANCH IN BRANCH.ID_BRANCH%TYPE) IS
BEGIN
  DELETE FROM BRANCH WHERE ID_BRANCH =  PID_BRANCH;
END DELETE_BRANCH;

CREATE OR REPLACE PROCEDURE CREATE_CATEGORY (PNAME IN CATEGORY.NAME%TYPE, PDESCRIPTION IN CATEGORY.DESCRIPTION%TYPE) AS
BEGIN
    INSERT INTO CATEGORY (ID_CATEGORY,NAME,DESCRIPTION) VALUES (SQ_CATEGORY.NEXTVAL,PNAME,PDESCRIPTION);
    COMMIT;
END;

CREATE OR REPLACE PROCEDURE UPDATE_CATEGORY (PID_CATEGORY IN CATEGORY.ID_CATEGORY%TYPE, PNAME IN CATEGORY.NAME%TYPE, PDESCRIPTION IN CATEGORY.DESCRIPTION%TYPE) AS
BEGIN
    UPDATE CATEGORY
    SET
    NAME = PNAME,
    DESCRIPTION = PDESCRIPTION
    WHERE
    ID_CATEGORY = PID_CATEGORY;
    COMMIT;
END;

CREATE OR REPLACE PROCEDURE DELETE_CATEGORY (PID_CATEGORY IN CATEGORY.ID_CATEGORY%TYPE) IS
BEGIN
  DELETE FROM CATEGORY WHERE ID_CATEGORY =  PID_CATEGORY;
END DELETE_CATEGORY;

CREATE OR REPLACE PROCEDURE CREATE_PRODUCT (PNAME_PRODUCT IN PRODUCT.NAME_PRODUCT%TYPE, PCREATED_PRODUCT IN PRODUCT.CREATED_PRODUCT%TYPE,
PID_CATEGORY IN PRODUCT.ID_CATEGORY%TYPE) AS
BEGIN 
    INSERT INTO PRODUCT(ID_PRODUCT,NAME_PRODUCT,CREATED_PRODUCT,ID_CATEGORY) VALUES (SQ_PRODUCT.NEXTVAL,PNAME_PRODUCT,PCREATED_PRODUCT,PID_CATEGORY);
    COMMIT;
END;

CREATE OR REPLACE PROCEDURE UPDATE_PRODUCT (PID_PRODUCT IN PRODUCT.ID_PRODUCT%TYPE, PNAME_PRODUCT IN PRODUCT.NAME_PRODUCT%TYPE, PCREATED_PRODUCT IN PRODUCT.CREATED_PRODUCT%TYPE,
PID_CATEGORY IN PRODUCT.ID_CATEGORY%TYPE) AS
BEGIN   
    UPDATE PRODUCT 
    SET
    NAME_PRODUCT = PNAME_PRODUCT,
    CREATED_PRODUCT = PCREATED_PRODUCT,
    ID_CATEGORY = PID_CATEGORY
    WHERE
    ID_PRODUCT = PID_PRODUCT;
    COMMIT;
END;

CREATE OR REPLACE PROCEDURE DELETE_PRODUCT (PID_PRODUCT IN PRODUCT.ID_PRODUCT%TYPE) IS
BEGIN
  DELETE FROM PRODUCT WHERE ID_PRODUCT =  PID_PRODUCT;
END DELETE_PRODUCT;

CREATE OR REPLACE PROCEDURE CREATE_PROVIDER (PNAME_PROVIDER IN PROVIDER.NAME_PROVIDER%TYPE, PNIT_PROVIDER IN PROVIDER.NIT_PROVIDER%TYPE,
PPHONE_PROVIDER IN PROVIDER.PHONE_PROVIDER%TYPE,PADDRESS_PROVIDER IN PROVIDER.ADDRESS_PROVIDER%TYPE) AS
BEGIN
    INSERT INTO PROVIDER (ID_PROVIDER,NAME_PROVIDER,NIT_PROVIDER,PHONE_PROVIDER,ADDRESS_PROVIDER) VALUES (SQ_PROVIDER.NEXTVAL,PNAME_PROVIDER,PNIT_PROVIDER,PPHONE_PROVIDER,PADDRESS_PROVIDER);
    COMMIT;
END;

CREATE OR REPLACE PROCEDURE UPDATE_PROVIDER (PID_PROVIDER IN PROVIDER.ID_PROVIDER%TYPE,PNAME_PROVIDER IN PROVIDER.NAME_PROVIDER%TYPE, PNIT_PROVIDER IN PROVIDER.NIT_PROVIDER%TYPE,
PPHONE_PROVIDER IN PROVIDER.PHONE_PROVIDER%TYPE,PADDRESS_PROVIDER IN PROVIDER.ADDRESS_PROVIDER%TYPE) AS
BEGIN 
    UPDATE PROVIDER
    SET
    NAME_PROVIDER = PNAME_PROVIDER,
    NIT_PROVIDER = PNIT_PROVIDER,
    PHONE_PROVIDER = PPHONE_PROVIDER,
    ADDRESS_PROVIDER = PADDRESS_PROVIDER
    WHERE
    ID_PROVIDER  = PID_PROVIDER;
    COMMIT;
END;

CREATE OR REPLACE PROCEDURE DELETE_PROVIDER (PID_PROVIDER IN PROVIDER.ID_PROVIDER%TYPE) IS
BEGIN
    DELETE FROM PROVIDER WHERE ID_PROVIDER = PID_PROVIDER;
END DELETE_PROVIDER;

CREATE OR REPLACE PROCEDURE CREATE_WAREHOUSE_USER(PNAME_USER IN WAREHOUSE_USER.NAME_USER%TYPE,PPHONE_USER IN WAREHOUSE_USER.PHONE_USER%TYPE,PJOB_TITLE WAREHOUSE_USER.JOB_TITLE%TYPE)AS
BEGIN
    INSERT INTO WAREHOUSE_USER (ID_USER,NAME_USER,PHONE_USER,JOB_TITLE) VALUES (SQ_WAREHOUSE_USER.NEXTVAL,PNAME_USER,PPHONE_USER,PJOB_TITLE);
    COMMIT;
END;

CREATE OR REPLACE PROCEDURE UPDATE_WAREHOUSE_USER(PID_USER IN WAREHOUSE_USER.ID_USER%TYPE,PNAME_USER IN WAREHOUSE_USER.NAME_USER%TYPE,PPHONE_USER IN WAREHOUSE_USER.PHONE_USER%TYPE,PJOB_TITLE WAREHOUSE_USER.JOB_TITLE%TYPE)AS
BEGIN

    UPDATE WAREHOUSE_USER
    SET
    NAME_USER = PNAME_USER,
    PHONE_USER = PPHONE_USER,
    JOB_TITLE = PJOB_TITLE
    WHERE
    ID_USER = PID_USER;
    COMMIT;
END; 

CREATE OR REPLACE PROCEDURE DELETE_WAREHOUSE_USER (PID_USER IN WAREHOUSE_USER.ID_USER%TYPE) IS
BEGIN
    DELETE FROM WAREHOUSE_USER WHERE ID_USER = PID_USER;
END DELETE_WAREHOUSE_USER ;

CREATE OR REPLACE PROCEDURE CREATE_N_ORDER(PDATE_TIME IN N_ORDER.DATE_TIME%TYPE, PTOTAL_AMOUNT IN N_ORDER.TOTAL_AMOUNT%TYPE)AS
BEGIN
    INSERT INTO N_ORDER (ID_ORDER,DATE_TIME,TOTAL_AMOUNT) VALUES (SQ_N_ORDER.NEXTVAL,PDATE_TIME,PTOTAL_AMOUNT);
    COMMIT;
END;

CREATE OR REPLACE PROCEDURE UPDATE_N_ORDER (PID_ORDER IN N_ORDER.ID_ORDER%TYPE, PDATE_TIME IN N_ORDER.DATE_TIME%TYPE, PTOTAL_AMOUNT IN N_ORDER.TOTAL_AMOUNT%TYPE)AS
BEGIN
    UPDATE N_ORDER
    SET 
    DATE_TIME = PDATE_TIME,
    TOTAL_AMOUNT = PTOTAL_AMOUNT
    WHERE
    ID_ORDER = PID_ORDER;
    COMMIT;
END;

CREATE OR REPLACE PROCEDURE DELETE_N_ORDER (PID_ORDER IN N_ORDER.ID_ORDER%TYPE) IS
BEGIN
    DELETE FROM N_ORDER WHERE ID_ORDER = PID_ORDER;
END DELETE_N_ORDER ;

CREATE OR REPLACE PROCEDURE CREATE_PROVIDER_BY_PRODUCT(PLAST_ADDED IN PROVIDER_BY_PRODUCT.LAST_ADDED%TYPE,PID_PROVIDER IN PROVIDER_BY_PRODUCT.ID_PROVIDER%TYPE,
PID_PRODUCT IN  PROVIDER_BY_PRODUCT.ID_PRODUCT%TYPE,PID_USER IN PROVIDER_BY_PRODUCT.ID_USER%TYPE,PQUANTITY IN PROVIDER_BY_PRODUCT.QUANTITY%TYPE,PPRICE_PRODUCT IN PROVIDER_BY_PRODUCT.PRICE_PRODUCT%TYPE)AS
BEGIN
    INSERT INTO PROVIDER_BY_PRODUCT (ID_PROVIDER_BY_PRODUCT,LAST_ADDED,ID_PROVIDER,ID_PRODUCT,ID_USER,QUANTITY,PRICE_PRODUCT) VALUES (SQ_PROVIDER_BY_PRODUCT.NEXTVAL,PLAST_ADDED,PID_PROVIDER,PID_PRODUCT,PID_USER,PQUANTITY,PPRICE_PRODUCT);
    COMMIT;
END;


CREATE OR REPLACE PROCEDURE UPDATE_PROVIDER_BY_PRODUCT (PID_PROVIDER_BY_PRODUCT IN PROVIDER_BY_PRODUCT.ID_PROVIDER_BY_PRODUCT%TYPE,PLAST_ADDED IN PROVIDER_BY_PRODUCT.LAST_ADDED%TYPE,PID_PROVIDER IN PROVIDER_BY_PRODUCT.ID_PROVIDER%TYPE,
PID_PRODUCT IN  PROVIDER_BY_PRODUCT.ID_PRODUCT%TYPE,PID_USER IN PROVIDER_BY_PRODUCT.ID_USER%TYPE,PQUANTITY IN PROVIDER_BY_PRODUCT.QUANTITY%TYPE,PPRICE_PRODUCT IN PROVIDER_BY_PRODUCT.PRICE_PRODUCT%TYPE)AS
BEGIN
    UPDATE PROVIDER_BY_PRODUCT
    SET 
    LAST_ADDED = PLAST_ADDED,
    ID_PROVIDER = PID_PROVIDER,
    ID_PRODUCT = PID_PRODUCT,
    ID_USER = PID_USER,
    QUANTITY = QUANTITY + PQUANTITY,
    PRICE_PRODUCT = PPRICE_PRODUCT
    WHERE
    ID_PROVIDER_BY_PRODUCT = PID_PROVIDER_BY_PRODUCT;
    COMMIT;
END;

CREATE OR REPLACE PROCEDURE DELETE_PROVIDER_BY_PRODUCT (PID_PROVIDER_BY_PRODUCT IN PROVIDER_BY_PRODUCT.ID_PROVIDER_BY_PRODUCT%TYPE) IS
BEGIN
    DELETE FROM PROVIDER_BY_PRODUCT WHERE ID_PROVIDER_BY_PRODUCT = PID_PROVIDER_BY_PRODUCT;
END DELETE_PROVIDER_BY_PRODUCT ;


CREATE OR REPLACE PROCEDURE CREATE_ORDER_DETAIL(PID_PROVIDER_BY_PRODUCT IN ORDER_DETAIL.ID_PROVIDER_BY_PRODUCT%TYPE,PQUATITY_IN IN ORDER_DETAIL.QUATITY_IN%TYPE,
PPRICE_BY_PRODUCT IN ORDER_DETAIL.PRICE_BY_PRODUCT%TYPE,PTOTAL_ORDER IN ORDER_DETAIL.TOTAL_ORDER%TYPE,PID_ORDER IN ORDER_DETAIL.ID_ORDER%TYPE)AS
BEGIN
    INSERT INTO ORDER_DETAIL (ID_DETAIL,ID_PROVIDER_BY_PRODUCT,QUATITY_IN,PRICE_BY_PRODUCT,TOTAL_ORDER,ID_ORDER) VALUES (SQ_ORDER_DETAIL.NEXTVAL,PID_PROVIDER_BY_PRODUCT,PQUATITY_IN,PPRICE_BY_PRODUCT,PTOTAL_ORDER,PID_ORDER);
    COMMIT;
END;

CREATE OR REPLACE PROCEDURE UPDATE_ORDER_DETAIL(PID_DETAIL IN ORDER_DETAIL.ID_DETAIL%TYPE,PID_PROVIDER_BY_PRODUCT IN ORDER_DETAIL.ID_PROVIDER_BY_PRODUCT%TYPE,PQUATITY_IN IN ORDER_DETAIL.QUATITY_IN%TYPE,
PPRICE_BY_PRODUCT IN ORDER_DETAIL.PRICE_BY_PRODUCT%TYPE,PTOTAL_ORDER IN ORDER_DETAIL.TOTAL_ORDER%TYPE,PID_ORDER IN ORDER_DETAIL.ID_ORDER%TYPE) AS
BEGIN
    UPDATE ORDER_DETAIL
    SET 
    ID_PROVIDER_BY_PRODUCT = PID_PROVIDER_BY_PRODUCT,
    QUATITY_IN = PQUATITY_IN,
    PRICE_BY_PRODUCT = PPRICE_BY_PRODUCT,
    TOTAL_ORDER = PTOTAL_ORDER,
    ID_ORDER = PID_ORDER
    WHERE
    ID_DETAIL = PID_DETAIL;
    COMMIT;
END;

CREATE OR REPLACE PROCEDURE DELETE_ORDER_DETAIL (PID_DETAIL IN ORDER_DETAIL.ID_DETAIL%TYPE) IS
BEGIN
    DELETE FROM ORDER_DETAIL WHERE ID_DETAIL= PID_DETAIL;
END DELETE_ORDER_DETAIL ;

CREATE OR REPLACE PROCEDURE CREATE_DISPATCH_BY_WAREHOUSE(PID_BRANCH IN DISPATCH_BY_WAREHOUSE.ID_BRANCH%TYPE , PID_USER IN DISPATCH_BY_WAREHOUSE.ID_USER%TYPE ,
PLAST_SENT IN DISPATCH_BY_WAREHOUSE.LAST_SENT%TYPE)AS
BEGIN
    INSERT INTO DISPATCH_BY_WAREHOUSE (ID_DISPATCH_BY_WAREHOUSE,ID_BRANCH,ID_USER,LAST_SENT ) VALUES (SQ_DISPATCH_BY_WAREHOUSE.NEXTVAL,PID_BRANCH,PID_USER,PLAST_SENT);
    COMMIT;
END;

CREATE OR REPLACE PROCEDURE UPDATE_DISPATCH_BY_WAREHOUSE (PID_DISPATCH_BY_WAREHOUSE IN DISPATCH_BY_WAREHOUSE.ID_DISPATCH_BY_WAREHOUSE%TYPE,PID_BRANCH IN DISPATCH_BY_WAREHOUSE.ID_BRANCH%TYPE , PID_USER IN DISPATCH_BY_WAREHOUSE.ID_USER%TYPE ,
PLAST_SENT IN DISPATCH_BY_WAREHOUSE.LAST_SENT%TYPE)AS
BEGIN
    UPDATE DISPATCH_BY_WAREHOUSE
    SET 
    ID_BRANCH = PID_BRANCH,
    ID_USER = PID_USER,
    LAST_SENT = PLAST_SENT
    WHERE
    ID_DISPATCH_BY_WAREHOUSE = PID_DISPATCH_BY_WAREHOUSE;
    COMMIT;
END;

CREATE OR REPLACE PROCEDURE DELETE_DISPATCH_BY_WAREHOUSE (PID_DISPATCH_BY_WAREHOUSE IN DISPATCH_BY_WAREHOUSE.ID_DISPATCH_BY_WAREHOUSE%TYPE) IS
BEGIN
    DELETE FROM DISPATCH_BY_WAREHOUSE WHERE ID_DISPATCH_BY_WAREHOUSE= PID_DISPATCH_BY_WAREHOUSE;
END DELETE_DISPATCH_BY_WAREHOUSE ;

CREATE OR REPLACE PROCEDURE CREATE_DISPATCH_DETAILS(PID_DISPATCH_BY_WAREHOUSE IN DISPATCH_DETAILS.ID_DISPATCH_BY_WAREHOUSE%TYPE , PQUANTITY_OUT IN DISPATCH_DETAILS.QUANTITY_OUT%TYPE,
PID_PROVIDER_BY_PRODUCT IN DISPATCH_DETAILS.ID_PROVIDER_BY_PRODUCT%TYPE)AS
BEGIN
    INSERT INTO DISPATCH_DETAILS (ID_DISPATCH,ID_DISPATCH_BY_WAREHOUSE,QUANTITY_OUT,ID_PROVIDER_BY_PRODUCT) VALUES (SQ_DISPATCH_DETAILS.NEXTVAL,PID_DISPATCH_BY_WAREHOUSE,PQUANTITY_OUT,PID_PROVIDER_BY_PRODUCT);
    COMMIT;
END;

CREATE OR REPLACE PROCEDURE UPDATE_DISPATCH_DETAILS(PID_DISPATCH IN DISPATCH_DETAILS.ID_DISPATCH%TYPE , PID_DISPATCH_BY_WAREHOUSE IN DISPATCH_DETAILS.ID_DISPATCH_BY_WAREHOUSE%TYPE , PQUANTITY_OUT IN DISPATCH_DETAILS.QUANTITY_OUT%TYPE,
PID_PROVIDER_BY_PRODUCT IN DISPATCH_DETAILS.ID_PROVIDER_BY_PRODUCT%TYPE)AS
BEGIN
    UPDATE DISPATCH_DETAILS
    SET 
    ID_DISPATCH_BY_WAREHOUSE = PID_DISPATCH_BY_WAREHOUSE,
    QUANTITY_OUT = PQUANTITY_OUT,
    ID_PROVIDER_BY_PRODUCT = PID_PROVIDER_BY_PRODUCT
    WHERE
    ID_DISPATCH = PID_DISPATCH;
    COMMIT;
END;

CREATE OR REPLACE PROCEDURE DELETE_DISPATCH_DETAILS (PID_DISPATCH IN DISPATCH_DETAILS.ID_DISPATCH%TYPE) IS
BEGIN
    DELETE FROM DISPATCH_DETAILS WHERE ID_DISPATCH = PID_DISPATCH;
    COMMIT;
END DELETE_DISPATCH_DETAILS ;



CREATE OR REPLACE TRIGGER PRODUCT_IN AFTER INSERT 
ON ORDER_DETAIL FOR EACH ROW
BEGIN
    UPDATE provider_by_product SET quantity = quantity + :new.quatity_in WHERE id_provider_by_product = :new.id_provider_by_product;
END;

CREATE OR REPLACE TRIGGER PRODUCT_OUT BEFORE INSERT 
ON DISPATCH_DETAILS FOR EACH ROW
DECLARE
    current_qty INTEGER;
    pragma autonomous_transaction;
BEGIN
    SELECT quantity INTO current_qty FROM provider_by_product where id_provider_by_product = :new.id_provider_by_product;
    IF (current_qty > :new.quantity_out) then
        UPDATE provider_by_product SET quantity = quantity - :new.quantity_out WHERE id_provider_by_product = :new.id_provider_by_product;
    ELSE 
          raise_application_error(-20000
                , 'Bodega insuficiente para el despacho.');
    END IF;
END;

SELECT no.id_order, p.name_product, ot.id_detail, pbp.id_provider_by_product, ot.quatity_in, pbp.quantity FROM N_ORDER NO 
INNER JOIN ORDER_DETAIL OT 
    ON NO.ID_ORDER = OT.ID_ORDER
INNER JOIN provider_by_product PBP 
    ON ot.id_provider_by_product = pbp.id_provider_by_product
INNER JOIN PRODUCT P ON pbp.id_product = p.id_product;