--SEQUENCIAS

CREATE SEQUENCE SQ_BRANCH INCREMENT BY 1 START WITH 1;

CREATE SEQUENCE SQ_CATEGORY INCREMENT BY 1 START WITH 1;

CREATE SEQUENCE SQ_DISPATCH_BY_WAREHOUSE INCREMENT BY 1 START WITH 1;

CREATE SEQUENCE SQ_DISPATCH_DETAILS INCREMENT BY 1 START WITH 1;

CREATE SEQUENCE SQ_N_ORDER INCREMENT BY 1 START WITH 1;
	
CREATE SEQUENCE SQ_ORDER_DETAIL INCREMENT BY 1 START WITH 1;

CREATE SEQUENCE SQ_PRODUCT INCREMENT BY 1 START WITH 1;

CREATE SEQUENCE SQ_PROVIDER INCREMENT BY 1 START WITH 1;

CREATE SEQUENCE SQ_PROVIDER_BY_PRODUCT INCREMENT BY 1 START WITH 1;
	
CREATE SEQUENCE SQ_WAREHOUSE_USER INCREMENT BY 1 START WITH 1;
	
--TABLAS

CREATE TABLE WAREHOUSE_USER (
    ID_USER     INTEGER NOT NULL PRIMARY KEY,
    NAME_USER   VARCHAR2(220) NOT NULL,
    PHONE_USER  VARCHAR2(11),
    JOB_TITLE   VARCHAR2(220)
);

CREATE TABLE BRANCH ( 
    ID_BRANCH       INTEGER NOT NULL PRIMARY KEY,
    NAME_BRANCH     VARCHAR2(120) NOT NULL,
    ADDRESS_BRANCH  VARCHAR2(220) NOT NULL,
    PHONE_BRANCH    VARCHAR2(11) NOT NULL
);

CREATE TABLE CATEGORY (
    ID_CATEGORY  INTEGER NOT NULL PRIMARY KEY,
    NAME         VARCHAR2(50),
    DESCRIPTION  VARCHAR2(100) 
);

CREATE TABLE N_ORDER (
    ID_ORDER      INTEGER NOT NULL PRIMARY KEY,
    DATE_TIME     DATE NOT NULL,
    TOTAL_AMOUNT  NUMBER(10, 2) NOT NULL
);

CREATE TABLE PRODUCT (
    ID_PRODUCT       INTEGER NOT NULL PRIMARY KEY,
    NAME_PRODUCT     VARCHAR2(120) NOT NULL,
    CREATED_PRODUCT  DATE NOT NULL,
    ID_CATEGORY INTEGER NOT NULL,
    CONSTRAINT PRODUCT_CATEGORY_FK FOREIGN KEY (ID_CATEGORY) REFERENCES   CATEGORY(ID_CATEGORY)
);


CREATE TABLE PROVIDER (
    ID_PROVIDER       INTEGER NOT NULL PRIMARY KEY,
    NAME_PROVIDER     VARCHAR2(250) NOT NULL,
    NIT_PROVIDER      VARCHAR2(15),
    PHONE_PROVIDER    VARCHAR2(11),
    ADDRESS_PROVIDER  VARCHAR2(220)
);


CREATE TABLE PROVIDER_BY_PRODUCT (
    ID_PROVIDER_BY_PRODUCT  INTEGER NOT NULL PRIMARY KEY,
    LAST_ADDED              DATE NOT NULL,
    ID_PROVIDER             INTEGER NOT NULL,
    ID_PRODUCT              INTEGER NOT NULL,
    ID_USER                 INTEGER NOT NULL,
    QUANTITY                INTEGER NOT NULL,
    PRICE_PRODUCT           FLOAT(10) NOT NULL,
    CONSTRAINT PROVIDER_DETAIL_FK FOREIGN KEY (ID_PROVIDER) REFERENCES   PROVIDER(ID_PROVIDER),
    CONSTRAINT PRODUCT_DETAIL_FK FOREIGN KEY (ID_PRODUCT) REFERENCES   PRODUCT(ID_PRODUCT),
    CONSTRAINT USER_DETAIL_FK FOREIGN KEY (ID_USER) REFERENCES   WAREHOUSE_USER(ID_USER)
);


CREATE TABLE ORDER_DETAIL (
    ID_DETAIL               INTEGER NOT NULL PRIMARY KEY,
    ID_PROVIDER_BY_PRODUCT  INTEGER NOT NULL,
    QUATITY_IN              INTEGER NOT NULL,
    PRICE_BY_PRODUCT        NUMBER (10,2) NOT NULL,
    ID_ORDER                INTEGER NOT NULL,
    CONSTRAINT PROV_PROD_DETAIL_FK FOREIGN KEY (ID_PROVIDER_BY_PRODUCT) REFERENCES   PROVIDER_BY_PRODUCT(ID_PROVIDER_BY_PRODUCT),
        CONSTRAINT ORDER_FK FOREIGN KEY (ID_ORDER) REFERENCES   N_ORDER(ID_ORDER)
);

CREATE TABLE DISPATCH_BY_WAREHOUSE (
    ID_DISPATCH_BY_WAREHOUSE  INTEGER NOT NULL PRIMARY KEY,
    ID_BRANCH                 INTEGER NOT NULL,
    ID_USER                   INTEGER NOT NULL,
    LAST_SENT                 DATE NOT NULL,
        CONSTRAINT BRANCH_DISPATCH_FK FOREIGN KEY (ID_BRANCH) REFERENCES   BRANCH(ID_BRANCH),
            CONSTRAINT USER_DISPATCH_FK FOREIGN KEY (ID_USER) REFERENCES   WAREHOUSE_USER(ID_USER)
);


CREATE TABLE DISPATCH_DETAILS (
    ID_DISPATCH               INTEGER NOT NULL PRIMARY KEY,
    ID_DISPATCH_BY_WAREHOUSE  INTEGER NOT NULL,
    QUANTITY_OUT              INTEGER NOT NULL,
    ID_PROVIDER_BY_PRODUCT    INTEGER NOT NULL,
    CONSTRAINT PROV_PROD1_DETAIL_FK FOREIGN KEY (ID_PROVIDER_BY_PRODUCT) REFERENCES   PROVIDER_BY_PRODUCT(ID_PROVIDER_BY_PRODUCT),
    CONSTRAINT DISPATCH1_DETAIL_FK FOREIGN KEY (ID_DISPATCH_BY_WAREHOUSE) REFERENCES   DISPATCH_BY_WAREHOUSE(ID_DISPATCH_BY_WAREHOUSE)
);


-----

--@JSONFORMAT(PATTERN="YYYY-MM-DD"), @JSONPROPERTY , @JSONPROPERTYORDER({"ID","DISPATCHWAREHOUSE","QUANTITYOUT","PROVIDERPRODUCT"}) ,	@JSONPROPERTY("ID") // ALIAS JSON CONVENCION TODO MINUSCULA. 


DROP TABLE BRANCH; 
DROP TABLE CATEGORY; 
DROP TABLE WAREHOUSE_USER; 
DROP TABLE PROVIDER; 
DROP TABLE DISPATCH_DETAILS;
DROP TABLE ORDER_DETAIL;
DROP TABLE PRODUCT; 
DROP TABLE DISPATCH_BY_WAREHOUSE;
DROP TABLE N_ORDER; 
DROP TABLE PROVIDER_BY_PRODUCT;


SELECT * FROM BRANCH;
SELECT * FROM CATEGORY;
SELECT * FROM PRODUCT;
SELECT * FROM PROVIDER;
SELECT * FROM WAREHOUSE_USER;
SELECT * FROM PROVIDER_BY_PRODUCT;
SELECT * FROM ORDER_DETAIL;
SELECT * FROM DISPATCH_BY_WAREHOUSE;
SELECT * FROM DISPATCH_DETAILS;

--- INSERTS

INSERT INTO BRANCH (ID_BRANCH, NAME_BRANCH,ADDRESS_BRANCH,PHONE_BRANCH)VALUES(1,'LAPOLA','LAS VEGAS','8184856105'); 
INSERT INTO BRANCH (ID_BRANCH, NAME_BRANCH,ADDRESS_BRANCH,PHONE_BRANCH)VALUES(2,'BOLANOS','LOS ANGELES','1001001012'); 

INSERT INTO CATEGORY (ID_CATEGORY,NAME,DESCRIPTION)VALUES (1,'ELECTRO DOMESTICOS','PRODUCTOS DE USO DEL HOGAR');
INSERT INTO CATEGORY (ID_CATEGORY,NAME,DESCRIPTION)VALUES (2,'CONSUMO BASICO','SE COMPRAN REGULARMENTE, NO PUEDEN FALTAR.');

INSERT INTO PRODUCT (ID_PRODUCT,NAME_PRODUCT,CREATED_PRODUCT,ID_CATEGORY) VALUES (1,'ESTUFA',TO_DATE('2020/04/17 20:01:43','YYYY/MM/DD HH24:MI:SS'),1);
INSERT INTO PRODUCT (ID_PRODUCT,NAME_PRODUCT,CREATED_PRODUCT,ID_CATEGORY) VALUES (2,'CAFE',TO_DATE('2020/04/17 20:01:43', 'YYYY/MM/DD HH24:MI:SS'),2);

INSERT INTO PROVIDER (ID_PROVIDER,NAME_PROVIDER,NIT_PROVIDER,PHONE_PROVIDER,ADDRESS_PROVIDER) VALUES (1,'UBERFREIHGT','10035230-8','2200000','MIXCO GUATEMALA');
INSERT INTO PROVIDER (ID_PROVIDER,NAME_PROVIDER,NIT_PROVIDER,PHONE_PROVIDER,ADDRESS_PROVIDER) VALUES (2,'LANDSTAR','109920-3','2300000','CIUDAD DE GUATEMALA');

INSERT INTO WAREHOUSE_USER (ID_USER,NAME_USER,PHONE_USER,JOB_TITLE) VALUES (1,'FERNANDO A', '5555-2222', 'OWNER');
INSERT INTO WAREHOUSE_USER (ID_USER,NAME_USER,PHONE_USER,JOB_TITLE) VALUES (2,'PEDRO F', '5555-2222', 'DBA');

INSERT INTO N_ORDER (ID_ORDER,DATE_TIME,TOTAL_AMOUNT) VALUES (1,TO_DATE('2020/04/17 20:01:43', 'YYYY/MM/DD HH24:MI:SS'),100.24);
INSERT INTO N_ORDER (ID_ORDER,DATE_TIME,TOTAL_AMOUNT) VALUES (2,TO_DATE('2020/04/17 20:01:43', 'YYYY/MM/DD HH24:MI:SS'),200.50);

INSERT INTO PROVIDER_BY_PRODUCT (ID_PROVIDER_BY_PRODUCT,LAST_ADDED,ID_PROVIDER,ID_PRODUCT,ID_USER,QUANTITY,PRICE_PRODUCT) VALUES (1,TO_DATE('2020/04/17 20:01:43','YYYY/MM/DD HH24:MI:SS'),1,2,1,100,125.50);
INSERT INTO PROVIDER_BY_PRODUCT (ID_PROVIDER_BY_PRODUCT,LAST_ADDED,ID_PROVIDER,ID_PRODUCT,ID_USER,QUANTITY,PRICE_PRODUCT) VALUES (2,TO_DATE('2020/04/19 20:01:43','YYYY/MM/DD HH24:MI:SS'),1,2,1,400,150.99);

INSERT INTO ORDER_DETAIL (ID_DETAIL,ID_PROVIDER_BY_PRODUCT,QUATITY_IN,PRICE_BY_PRODUCT,TOTAL_ORDER,ID_ORDER) VALUES (1,1,100,150.55,300.50,1);
INSERT INTO ORDER_DETAIL (ID_DETAIL,ID_PROVIDER_BY_PRODUCT,QUATITY_IN,PRICE_BY_PRODUCT,TOTAL_ORDER,ID_ORDER) VALUES (2,2,400,350.55,1300.50,2);

INSERT INTO DISPATCH_BY_WAREHOUSE (ID_DISPATCH_BY_WAREHOUSE,ID_BRANCH,ID_USER,LAST_SENT ) VALUES (1,1,1,TO_DATE('2020/04/17 20:01:43', 'YYYY/MM/DD HH24:MI:SS'));
INSERT INTO DISPATCH_BY_WAREHOUSE (ID_DISPATCH_BY_WAREHOUSE,ID_BRANCH,ID_USER,LAST_SENT ) VALUES (2,2,2,TO_DATE('2020/05/25 20:01:43', 'YYYY/MM/DD HH24:MI:SS'));

INSERT INTO DISPATCH_DETAILS (ID_DISPATCH,ID_DISPATCH_BY_WAREHOUSE,QUANTITY_OUT,ID_PROVIDER_BY_PRODUCT) VALUES (1,1,100,2);
INSERT INTO DISPATCH_DETAILS (ID_DISPATCH,ID_DISPATCH_BY_WAREHOUSE,QUANTITY_OUT,ID_PROVIDER_BY_PRODUCT) VALUES (2,2,10,1);


--BRANCH

--PROCEDIMIENTOS CRUD BRANCH
--CREATE
CREATE OR REPLACE PROCEDURE CREATE_BRANCH (PNAME_BRANCH IN BRANCH.NAME_BRANCH%TYPE,PADDRESS_BRANCH IN BRANCH.ADDRESS_BRANCH%TYPE,PPHONE_BRANCH IN BRANCH.PHONE_BRANCH%TYPE) AS
BEGIN
  INSERT INTO BRANCH (ID_BRANCH,NAME_BRANCH,ADDRESS_BRANCH,PHONE_BRANCH) VALUES (SQ_BRANCH.NEXTVAL,PNAME_BRANCH,PADDRESS_BRANCH,PPHONE_BRANCH);
  COMMIT;
END;

CALL CREATE_BRANCH ('JIFFY','MIXCO','4754-5847');


--UPDATE
CREATE OR REPLACE PROCEDURE UPDATE_BRANCH (PID_BRANCH IN BRANCH.ID_BRANCH%TYPE, PNAME_BRANCH IN BRANCH.NAME_BRANCH%TYPE,PADDRESS_BRANCH IN BRANCH.ADDRESS_BRANCH%TYPE,PPHONE_BRANCH IN BRANCH.PHONE_BRANCH%TYPE) AS
BEGIN
  UPDATE BRANCH
  SET 
  NAME_BRANCH = PNAME_BRANCH, ADDRESS_BRANCH = PADDRESS_BRANCH , PHONE_BRANCH = PPHONE_BRANCH
  WHERE
  ID_BRANCH = PID_BRANCH;
  COMMIT;
END;

CALL UPDATE_BRANCH(4,'EL FOX','LOS OLIVOS','5555-2222');

--DELETE
CREATE OR REPLACE PROCEDURE DELETE_BRANCH (PID_BRANCH IN BRANCH.ID_BRANCH%TYPE) IS
BEGIN
  DELETE FROM BRANCH WHERE ID_BRANCH =  PID_BRANCH;
END DELETE_BRANCH;

BEGIN
   DELETE_BRANCH(3);
END;


--CATEGORY

--PROCEDIMIENTOS CRUD CATEGORY
--CREATE
CREATE OR REPLACE PROCEDURE CREATE_CATEGORY (PNAME IN CATEGORY.NAME%TYPE, PDESCRIPTION IN CATEGORY.DESCRIPTION%TYPE) AS
BEGIN
    INSERT INTO CATEGORY (ID_CATEGORY,NAME,DESCRIPTION) VALUES (SQ_CATEGORY.NEXTVAL,PNAME,PDESCRIPTION);
    COMMIT;
END;

CALL CREATE_CATEGORY('ALIMENTOS','ALIMENTOS NO REFRIGERADOS');

--UPDATE
CREATE OR REPLACE PROCEDURE UPDATE_CATEGORY (PID_CATEGORY IN CATEGORY.ID_CATEGORY%TYPE, PNAME IN CATEGORY.NAME%TYPE, PDESCRIPTION IN CATEGORY.DESCRIPTION%TYPE) AS
BEGIN
    UPDATE CATEGORY
    SET
    NAME = PNAME,
    DESCRIPTION = PDESCRIPTION
    WHERE
    ID_CATEGORY = PID_CATEGORY;
    COMMIT;
END;

CALL UPDATE_CATEGORY(3,'COMIDA PERROS','ALIMENTOS NO REFRIGERADOS');

--DELETE
CREATE OR REPLACE PROCEDURE DELETE_CATEGORY (PID_CATEGORY IN CATEGORY.ID_CATEGORY%TYPE) IS
BEGIN
  DELETE FROM CATEGORY WHERE ID_CATEGORY =  PID_CATEGORY;
END DELETE_CATEGORY;

BEGIN
   DELETE_CATEGORY(3);
END;

--PRODUCT

--PROCEDIMIENTOS CRUD PRODUCT
--CREATE
CREATE OR REPLACE PROCEDURE CREATE_PRODUCT (PNAME_PRODUCT IN PRODUCT.NAME_PRODUCT%TYPE, PCREATED_PRODUCT IN PRODUCT.CREATED_PRODUCT%TYPE,
PID_CATEGORY IN PRODUCT.ID_CATEGORY%TYPE) AS
BEGIN 
    INSERT INTO PRODUCT(ID_PRODUCT,NAME_PRODUCT,CREATED_PRODUCT,ID_CATEGORY) VALUES (SQ_PRODUCT.NEXTVAL,PNAME_PRODUCT,PCREATED_PRODUCT,PID_CATEGORY);
    COMMIT;
END;

CALL CREATE_PRODUCT('PEPSI',SYSDATE,2);

--UPDATE
CREATE OR REPLACE PROCEDURE UPDATE_PRODUCT (PID_PRODUCT IN PRODUCT.ID_PRODUCT%TYPE, PNAME_PRODUCT IN PRODUCT.NAME_PRODUCT%TYPE, PCREATED_PRODUCT IN PRODUCT.CREATED_PRODUCT%TYPE,
PID_CATEGORY IN PRODUCT.ID_CATEGORY%TYPE) AS
BEGIN   
    UPDATE PRODUCT 
    SET
    NAME_PRODUCT = PNAME_PRODUCT,
    CREATED_PRODUCT = PCREATED_PRODUCT,
    ID_CATEGORY = PID_CATEGORY
    WHERE
    ID_PRODUCT = PID_PRODUCT;
    COMMIT;
END;

CALL UPDATE_PRODUCT(4,'7UP',SYSDATE,2);

--DELETE
CREATE OR REPLACE PROCEDURE DELETE_PRODUCT (PID_PRODUCT IN PRODUCT.ID_PRODUCT%TYPE) IS
BEGIN
  DELETE FROM PRODUCT WHERE ID_PRODUCT =  PID_PRODUCT;
END DELETE_PRODUCT;

BEGIN
   DELETE_PRODUCT(4);
END;

--PROVIDER

--PROCEDIMIENTOS CRUD PROVIDER
--CREATE
CREATE OR REPLACE PROCEDURE CREATE_PROVIDER (PNAME_PROVIDER IN PROVIDER.NAME_PROVIDER%TYPE, PNIT_PROVIDER IN PROVIDER.NIT_PROVIDER%TYPE,
PPHONE_PROVIDER IN PROVIDER.PHONE_PROVIDER%TYPE,PADDRESS_PROVIDER IN PROVIDER.ADDRESS_PROVIDER%TYPE) AS
BEGIN
    INSERT INTO PROVIDER (ID_PROVIDER,NAME_PROVIDER,NIT_PROVIDER,PHONE_PROVIDER,ADDRESS_PROVIDER) VALUES (SQ_PROVIDER.NEXTVAL,PNAME_PROVIDER,PNIT_PROVIDER,PPHONE_PROVIDER,PADDRESS_PROVIDER);
    COMMIT;
END;

CALL CREATE_PROVIDER('UBERFREIHGT','10035230-8','2200000','MIXCO GUATEMALA');

--UPDATE
CREATE OR REPLACE PROCEDURE UPDATE_PROVIDER (PID_PROVIDER IN PROVIDER.ID_PROVIDER%TYPE,PNAME_PROVIDER IN PROVIDER.NAME_PROVIDER%TYPE, PNIT_PROVIDER IN PROVIDER.NIT_PROVIDER%TYPE,
PPHONE_PROVIDER IN PROVIDER.PHONE_PROVIDER%TYPE,PADDRESS_PROVIDER IN PROVIDER.ADDRESS_PROVIDER%TYPE) AS
BEGIN 
    UPDATE PROVIDER
    SET
    NAME_PROVIDER = PNAME_PROVIDER,
    NIT_PROVIDER = PNIT_PROVIDER,
    PHONE_PROVIDER = PPHONE_PROVIDER,
    ADDRESS_PROVIDER = PADDRESS_PROVIDER
    WHERE
    ID_PROVIDER  = PID_PROVIDER;
    COMMIT;
END;

CALL UPDATE_PROVIDER(3,'AQ TRANS','10035230-8','2200000','MIXCO GUATEMALA');

--DELETE
CREATE OR REPLACE PROCEDURE DELETE_PROVIDER (PID_PROVIDER IN PROVIDER.ID_PROVIDER%TYPE) IS
BEGIN
    DELETE FROM PROVIDER WHERE ID_PROVIDER = PID_PROVIDER;
END DELETE_PROVIDER;

BEGIN
    DELETE_PROVIDER(3);
END;

--WAREHOUSE_USER

--PROCEDIMIENTOS CRUD WAREHOUSE_USER
--CREATE
CREATE OR REPLACE PROCEDURE CREATE_WAREHOUSE_USER(PNAME_USER IN WAREHOUSE_USER.NAME_USER%TYPE,PPHONE_USER IN WAREHOUSE_USER.PHONE_USER%TYPE,PJOB_TITLE WAREHOUSE_USER.JOB_TITLE%TYPE)AS
BEGIN
    INSERT INTO WAREHOUSE_USER (ID_USER,NAME_USER,PHONE_USER,JOB_TITLE) VALUES (SQ_WAREHOUSE_USER.NEXTVAL,PNAME_USER,PPHONE_USER,PJOB_TITLE);
    COMMIT;
END;

CALL CREATE_WAREHOUSE_USER ('FERNANDO A', '5555-2222', 'OWNER');

--UPDATE
CREATE OR REPLACE PROCEDURE UPDATE_WAREHOUSE_USER(PID_USER IN WAREHOUSE_USER.ID_USER%TYPE,PNAME_USER IN WAREHOUSE_USER.NAME_USER%TYPE,PPHONE_USER IN WAREHOUSE_USER.PHONE_USER%TYPE,PJOB_TITLE WAREHOUSE_USER.JOB_TITLE%TYPE)AS
BEGIN

    UPDATE WAREHOUSE_USER
    SET
    NAME_USER = PNAME_USER,
    PHONE_USER = PPHONE_USER,
    JOB_TITLE = PJOB_TITLE
    WHERE
    ID_USER = PID_USER;
    COMMIT;
END; 

CALL UPDATE_WAREHOUSE_USER (3,'CELSO ROJAS', '5555-2222', 'OWNER'); 

--DELETE
CREATE OR REPLACE PROCEDURE DELETE_WAREHOUSE_USER (PID_USER IN WAREHOUSE_USER.ID_USER%TYPE) IS
BEGIN
    DELETE FROM WAREHOUSE_USER WHERE ID_USER = PID_USER;
END DELETE_WAREHOUSE_USER ;

BEGIN
    DELETE_WAREHOUSE_USER (3);
END;

--ORDER

--PROCEDIMIENTOS CRUD N_ORDER
--CREATE
CREATE OR REPLACE PROCEDURE CREATE_N_ORDER(PDATE_TIME IN N_ORDER.DATE_TIME%TYPE, PTOTAL_AMOUNT IN N_ORDER.TOTAL_AMOUNT%TYPE)AS
BEGIN
    INSERT INTO N_ORDER (ID_ORDER,DATE_TIME,TOTAL_AMOUNT) VALUES (SQ_N_ORDER.NEXTVAL,PDATE_TIME,PTOTAL_AMOUNT);
    COMMIT;
END;

CALL CREATE_N_ORDER (SYSDATE,100.24);

--UPDATE
CREATE OR REPLACE PROCEDURE UPDATE_N_ORDER (PID_ORDER IN N_ORDER.ID_ORDER%TYPE, PDATE_TIME IN N_ORDER.DATE_TIME%TYPE, PTOTAL_AMOUNT IN N_ORDER.TOTAL_AMOUNT%TYPE)AS
BEGIN
    UPDATE N_ORDER
    SET 
    DATE_TIME = PDATE_TIME,
    TOTAL_AMOUNT = PTOTAL_AMOUNT
    WHERE
    ID_ORDER = PID_ORDER;
    COMMIT;
END;

CALL UPDATE_N_ORDER (3,SYSDATE,100.24);

--DELETE
CREATE OR REPLACE PROCEDURE DELETE_N_ORDER (PID_ORDER IN N_ORDER.ID_ORDER%TYPE) IS
BEGIN
    DELETE FROM N_ORDER WHERE ID_ORDER = PID_ORDER;
END DELETE_N_ORDER ;

BEGIN
    DELETE_N_ORDER (1);
END;

--PROVIDER_BY_PRODUCT

--PROCEDIMIENTOS CRUD PROVIDER_BY_PRODUCT
--CREATE
CREATE OR REPLACE PROCEDURE CREATE_PROVIDER_BY_PRODUCT(PLAST_ADDED IN PROVIDER_BY_PRODUCT.LAST_ADDED%TYPE,PID_PROVIDER IN PROVIDER_BY_PRODUCT.ID_PROVIDER%TYPE,
PID_PRODUCT IN  PROVIDER_BY_PRODUCT.ID_PRODUCT%TYPE,PID_USER IN PROVIDER_BY_PRODUCT.ID_USER%TYPE,PQUANTITY IN PROVIDER_BY_PRODUCT.QUANTITY%TYPE,PPRICE_PRODUCT IN PROVIDER_BY_PRODUCT.PRICE_PRODUCT%TYPE)AS
BEGIN
    INSERT INTO PROVIDER_BY_PRODUCT (ID_PROVIDER_BY_PRODUCT,LAST_ADDED,ID_PROVIDER,ID_PRODUCT,ID_USER,QUANTITY,PRICE_PRODUCT) VALUES (SQ_PROVIDER_BY_PRODUCT.NEXTVAL,PLAST_ADDED,PID_PROVIDER,PID_PRODUCT,PID_USER,PQUANTITY,PPRICE_PRODUCT);
    COMMIT;
END;

CALL CREATE_PROVIDER_BY_PRODUCT (SYSDATE,1,2,1,100,125.50);

--UPDATE

CREATE OR REPLACE PROCEDURE UPDATE_PROVIDER_BY_PRODUCT (PID_PROVIDER_BY_PRODUCT IN PROVIDER_BY_PRODUCT.ID_PROVIDER_BY_PRODUCT%TYPE,PLAST_ADDED IN PROVIDER_BY_PRODUCT.LAST_ADDED%TYPE,PID_PROVIDER IN PROVIDER_BY_PRODUCT.ID_PROVIDER%TYPE,
PID_PRODUCT IN  PROVIDER_BY_PRODUCT.ID_PRODUCT%TYPE,PID_USER IN PROVIDER_BY_PRODUCT.ID_USER%TYPE,PQUANTITY IN PROVIDER_BY_PRODUCT.QUANTITY%TYPE,PPRICE_PRODUCT IN PROVIDER_BY_PRODUCT.PRICE_PRODUCT%TYPE)AS
BEGIN
    UPDATE PROVIDER_BY_PRODUCT
    SET 
    LAST_ADDED = PLAST_ADDED,
    ID_PROVIDER = PID_PROVIDER,
    ID_PRODUCT = PID_PRODUCT,
    ID_USER = PID_USER,
    QUANTITY = QUANTITY + PQUANTITY,
    PRICE_PRODUCT = PPRICE_PRODUCT
    WHERE
    ID_PROVIDER_BY_PRODUCT = PID_PROVIDER_BY_PRODUCT;
    COMMIT;
END;

CALL UPDATE_PROVIDER_BY_PRODUCT (3,TO_DATE('1998/04/17 20:01:43','YYYY/MM/DD HH24:MI:SS'),1,2,1,100,125.50);


--DELETE

CREATE OR REPLACE PROCEDURE DELETE_PROVIDER_BY_PRODUCT (PID_PROVIDER_BY_PRODUCT IN PROVIDER_BY_PRODUCT.ID_PROVIDER_BY_PRODUCT%TYPE) IS
BEGIN
    DELETE FROM PROVIDER_BY_PRODUCT WHERE ID_PROVIDER_BY_PRODUCT = PID_PROVIDER_BY_PRODUCT;
END DELETE_PROVIDER_BY_PRODUCT ;

BEGIN
    DELETE_PROVIDER_BY_PRODUCT (3);
END;


--ORDER_DETAIL

--PROCEDIMIENTOS CRUD ORDER_DETAIL
--CREATE
CREATE OR REPLACE PROCEDURE CREATE_ORDER_DETAIL(PID_PROVIDER_BY_PRODUCT IN ORDER_DETAIL.ID_PROVIDER_BY_PRODUCT%TYPE,PQUATITY_IN IN ORDER_DETAIL.QUATITY_IN%TYPE,
PPRICE_BY_PRODUCT IN ORDER_DETAIL.PRICE_BY_PRODUCT%TYPE,PID_ORDER IN ORDER_DETAIL.ID_ORDER%TYPE)AS
BEGIN
    INSERT INTO ORDER_DETAIL (ID_DETAIL,ID_PROVIDER_BY_PRODUCT,QUATITY_IN,PRICE_BY_PRODUCT,ID_ORDER) VALUES (SQ_ORDER_DETAIL.NEXTVAL,PID_PROVIDER_BY_PRODUCT,PQUATITY_IN,PPRICE_BY_PRODUCT,PID_ORDER);
    COMMIT;
END;

CALL CREATE_ORDER_DETAIL (1,100,150.55,1);

--UPDATE
CREATE OR REPLACE PROCEDURE UPDATE_ORDER_DETAIL(PID_DETAIL IN ORDER_DETAIL.ID_DETAIL%TYPE,PID_PROVIDER_BY_PRODUCT IN ORDER_DETAIL.ID_PROVIDER_BY_PRODUCT%TYPE,PQUATITY_IN IN ORDER_DETAIL.QUATITY_IN%TYPE,
PPRICE_BY_PRODUCT IN ORDER_DETAIL.PRICE_BY_PRODUCT%TYPE,PID_ORDER IN ORDER_DETAIL.ID_ORDER%TYPE) AS
BEGIN
    UPDATE ORDER_DETAIL
    SET 
    ID_PROVIDER_BY_PRODUCT = PID_PROVIDER_BY_PRODUCT,
    QUATITY_IN = PQUATITY_IN,
    PRICE_BY_PRODUCT = PPRICE_BY_PRODUCT,
    ID_ORDER = PID_ORDER
    WHERE
    ID_DETAIL = PID_DETAIL;
    COMMIT;
END;

CALL UPDATE_ORDER_DETAIL (3,1,400,150.55,1);

--DELETE

CREATE OR REPLACE PROCEDURE DELETE_ORDER_DETAIL (PID_DETAIL IN ORDER_DETAIL.ID_DETAIL%TYPE) IS
BEGIN
    DELETE FROM ORDER_DETAIL WHERE ID_DETAIL= PID_DETAIL;
END DELETE_ORDER_DETAIL ;

BEGIN
    DELETE_ORDER_DETAIL (3);
END;

--DISPATCH_BY_WAREHOUSE

--PROCEDIMIENTOS CRUD DISPATCH_BY_WAREHOUSE
--CREATE
CREATE OR REPLACE PROCEDURE CREATE_DISPATCH_BY_WAREHOUSE(PID_BRANCH IN DISPATCH_BY_WAREHOUSE.ID_BRANCH%TYPE , PID_USER IN DISPATCH_BY_WAREHOUSE.ID_USER%TYPE ,
PLAST_SENT IN DISPATCH_BY_WAREHOUSE.LAST_SENT%TYPE)AS
BEGIN
    INSERT INTO DISPATCH_BY_WAREHOUSE (ID_DISPATCH_BY_WAREHOUSE,ID_BRANCH,ID_USER,LAST_SENT ) VALUES (SQ_DISPATCH_BY_WAREHOUSE.NEXTVAL,PID_BRANCH,PID_USER,PLAST_SENT);
    COMMIT;
END;

CALL CREATE_DISPATCH_BY_WAREHOUSE (1,1,SYSDATE);

--UPDATE
CREATE OR REPLACE PROCEDURE UPDATE_DISPATCH_BY_WAREHOUSE (PID_DISPATCH_BY_WAREHOUSE IN DISPATCH_BY_WAREHOUSE.ID_DISPATCH_BY_WAREHOUSE%TYPE,PID_BRANCH IN DISPATCH_BY_WAREHOUSE.ID_BRANCH%TYPE , PID_USER IN DISPATCH_BY_WAREHOUSE.ID_USER%TYPE ,
PLAST_SENT IN DISPATCH_BY_WAREHOUSE.LAST_SENT%TYPE)AS
BEGIN
    UPDATE DISPATCH_BY_WAREHOUSE
    SET 
    ID_BRANCH = PID_BRANCH,
    ID_USER = PID_USER,
    LAST_SENT = PLAST_SENT
    WHERE
    ID_DISPATCH_BY_WAREHOUSE = PID_DISPATCH_BY_WAREHOUSE;
    COMMIT;
END;

CALL UPDATE_DISPATCH_BY_WAREHOUSE (3,1,1,SYSDATE);

--DELETE
CREATE OR REPLACE PROCEDURE DELETE_DISPATCH_BY_WAREHOUSE (PID_DISPATCH_BY_WAREHOUSE IN DISPATCH_BY_WAREHOUSE.ID_DISPATCH_BY_WAREHOUSE%TYPE) IS
BEGIN
    DELETE FROM DISPATCH_BY_WAREHOUSE WHERE ID_DISPATCH_BY_WAREHOUSE= PID_DISPATCH_BY_WAREHOUSE;
END DELETE_DISPATCH_BY_WAREHOUSE ;

BEGIN
    DELETE_DISPATCH_BY_WAREHOUSE (3);
END;

--DISPATCH_DETAILS

--PROCEDIMIENTOS CRUD --DISPATCH_DETAILS

--CREATE
CREATE OR REPLACE PROCEDURE CREATE_DISPATCH_DETAILS(PID_DISPATCH_BY_WAREHOUSE IN DISPATCH_DETAILS.ID_DISPATCH_BY_WAREHOUSE%TYPE , PQUANTITY_OUT IN DISPATCH_DETAILS.QUANTITY_OUT%TYPE,
PID_PROVIDER_BY_PRODUCT IN DISPATCH_DETAILS.ID_PROVIDER_BY_PRODUCT%TYPE)AS
BEGIN
    INSERT INTO DISPATCH_DETAILS (ID_DISPATCH,ID_DISPATCH_BY_WAREHOUSE,QUANTITY_OUT,ID_PROVIDER_BY_PRODUCT) VALUES (SQ_DISPATCH_DETAILS.NEXTVAL,PID_DISPATCH_BY_WAREHOUSE,PQUANTITY_OUT,PID_PROVIDER_BY_PRODUCT);
    COMMIT;
END;

CALL CREATE_DISPATCH_DETAILS (1,100,2);

--UPDATE
CREATE OR REPLACE PROCEDURE UPDATE_DISPATCH_DETAILS(PID_DISPATCH IN DISPATCH_DETAILS.ID_DISPATCH%TYPE , PID_DISPATCH_BY_WAREHOUSE IN DISPATCH_DETAILS.ID_DISPATCH_BY_WAREHOUSE%TYPE , PQUANTITY_OUT IN DISPATCH_DETAILS.QUANTITY_OUT%TYPE,
PID_PROVIDER_BY_PRODUCT IN DISPATCH_DETAILS.ID_PROVIDER_BY_PRODUCT%TYPE)AS
BEGIN
    UPDATE DISPATCH_DETAILS
    SET 
    ID_DISPATCH_BY_WAREHOUSE = PID_DISPATCH_BY_WAREHOUSE,
    QUANTITY_OUT = PQUANTITY_OUT,
    ID_PROVIDER_BY_PRODUCT = PID_PROVIDER_BY_PRODUCT
    WHERE
    ID_DISPATCH = PID_DISPATCH;
    COMMIT;
END;

CALL UPDATE_DISPATCH_DETAILS (3,1,200,2);

--DELETE
CREATE OR REPLACE PROCEDURE DELETE_DISPATCH_DETAILS (PID_DISPATCH IN DISPATCH_DETAILS.ID_DISPATCH%TYPE) IS
BEGIN
    DELETE FROM DISPATCH_DETAILS WHERE ID_DISPATCH = PID_DISPATCH;
    COMMIT;
END DELETE_DISPATCH_DETAILS ;

BEGIN
    DELETE_DISPATCH_DETAILS (3);
END;

