insert into CATEGORY (ID_CATEGORY, NAME, DESCRIPTION) values (1, 'egestas', 'Face to face systemic concept');
insert into CATEGORY (ID_CATEGORY, NAME, DESCRIPTION) values (2, 'sit', 'Visionary intermediate task-force');
insert into CATEGORY (ID_CATEGORY, NAME, DESCRIPTION) values (3, 'neque', 'Total responsive paradigm');
insert into CATEGORY (ID_CATEGORY, NAME, DESCRIPTION) values (4, 'pede', 'Front-line discrete matrices');
insert into CATEGORY (ID_CATEGORY, NAME, DESCRIPTION) values (5, 'vitae', 'Horizontal value-added hardware');
insert into CATEGORY (ID_CATEGORY, NAME, DESCRIPTION) values (6, 'sed', 'Organic contextually-based task-force');
insert into CATEGORY (ID_CATEGORY, NAME, DESCRIPTION) values (7, 'nisi', 'Robust non-volatile data-warehouse');
insert into CATEGORY (ID_CATEGORY, NAME, DESCRIPTION) values (8, 'sem', 'Networked mobile budgetary management');
insert into CATEGORY (ID_CATEGORY, NAME, DESCRIPTION) values (9, 'potenti', 'Sharable next generation conglomeration');
insert into CATEGORY (ID_CATEGORY, NAME, DESCRIPTION) values (10, 'tincidunt', 'Grass-roots system-worthy Graphic Interface');
insert into CATEGORY (ID_CATEGORY, NAME, DESCRIPTION) values (11, 'odio', 'Progressive 4th generation middleware');
insert into CATEGORY (ID_CATEGORY, NAME, DESCRIPTION) values (12, 'aliquam', 'Intuitive bi-directional portal');
insert into CATEGORY (ID_CATEGORY, NAME, DESCRIPTION) values (13, 'integer', 'Profit-focused neutral capacity');
insert into CATEGORY (ID_CATEGORY, NAME, DESCRIPTION) values (14, 'dui', 'Customizable incremental open system');
insert into CATEGORY (ID_CATEGORY, NAME, DESCRIPTION) values (15, 'ac', 'Intuitive radical artificial intelligence');
insert into CATEGORY (ID_CATEGORY, NAME, DESCRIPTION) values (16, 'eu', 'Monitored foreground monitoring');
insert into CATEGORY (ID_CATEGORY, NAME, DESCRIPTION) values (17, 'tortor', 'Grass-roots didactic conglomeration');
insert into CATEGORY (ID_CATEGORY, NAME, DESCRIPTION) values (18, 'erat', 'Robust encompassing methodology');
insert into CATEGORY (ID_CATEGORY, NAME, DESCRIPTION) values (19, 'duis', 'Devolved bi-directional adapter');
insert into CATEGORY (ID_CATEGORY, NAME, DESCRIPTION) values (20, 'ullamcorper', 'Polarised neutral instruction set');
insert into CATEGORY (ID_CATEGORY, NAME, DESCRIPTION) values (21, 'nascetur', 'Visionary upward-trending array');
insert into CATEGORY (ID_CATEGORY, NAME, DESCRIPTION) values (22, 'nunc', 'Upgradable multimedia leverage');
insert into CATEGORY (ID_CATEGORY, NAME, DESCRIPTION) values (23, 'sit', 'Realigned bi-directional parallelism');
insert into CATEGORY (ID_CATEGORY, NAME, DESCRIPTION) values (24, 'sed', 'Universal local internet solution');
insert into CATEGORY (ID_CATEGORY, NAME, DESCRIPTION) values (25, 'phasellus', 'Switchable demand-driven leverage');
insert into CATEGORY (ID_CATEGORY, NAME, DESCRIPTION) values (26, 'convallis', 'Streamlined user-facing intranet');
insert into CATEGORY (ID_CATEGORY, NAME, DESCRIPTION) values (27, 'pulvinar', 'Synergized upward-trending parallelism');
insert into CATEGORY (ID_CATEGORY, NAME, DESCRIPTION) values (28, 'commodo', 'Self-enabling value-added intranet');
insert into CATEGORY (ID_CATEGORY, NAME, DESCRIPTION) values (29, 'nisi', 'Compatible grid-enabled success');
insert into CATEGORY (ID_CATEGORY, NAME, DESCRIPTION) values (30, 'auctor', 'Enterprise-wide demand-driven system engine');
