SELECT MAX(ID_BRANCH) FROM BRANCH;

DROP SEQUENCE SQ_BRANCH;

CREATE SEQUENCE SQ_BRANCH INCREMENT BY 1 START WITH 501;


SELECT MAX(ID_CATEGORY) FROM CATEGORY;

DROP SEQUENCE SQ_CATEGORY;

CREATE SEQUENCE SQ_CATEGORY INCREMENT BY 1 START WITH 31;


SELECT MAX(ID_PRODUCT) FROM PRODUCT;

DROP SEQUENCE SQ_PRODUCT;

CREATE SEQUENCE SQ_PRODUCT INCREMENT BY 1 START WITH 1001;


SELECT MAX(ID_PROVIDER) FROM PROVIDER;

DROP SEQUENCE SQ_PROVIDER;

CREATE SEQUENCE SQ_PROVIDER INCREMENT BY 1 START WITH 101;


SELECT MAX(ID_PROVIDER_BY_PRODUCT) FROM PROVIDER_BY_PRODUCT;

DROP SEQUENCE SQ_PROVIDER_BY_PRODUCT;

CREATE SEQUENCE SQ_PROVIDER_BY_PRODUCT INCREMENT BY 1 START WITH 1001;


SELECT MAX(ID_ORDER) FROM N_ORDER;

DROP SEQUENCE SQ_N_ORDER;

CREATE SEQUENCE SQ_N_ORDER INCREMENT BY 1 START WITH 501;


SELECT MAX(ID_DETAIL) FROM ORDER_DETAIL;

DROP SEQUENCE SQ_ORDER_DETAIL;

CREATE SEQUENCE SQ_ORDER_DETAIL INCREMENT BY 1 START WITH 501;


SELECT MAX(ID_DISPATCH_BY_WAREHOUSE) FROM DISPATCH_BY_WAREHOUSE;

DROP SEQUENCE SQ_DISPATCH_BY_WAREHOUSE;

CREATE SEQUENCE SQ_DISPATCH_BY_WAREHOUSE INCREMENT BY 1 START WITH 501;

select * from DISPATCH_DETAILS;

select * from provider_by_product;
select * from dispatch_by_warehouse;
CALL CREATE_DISPATCH_DETAILS (210,100,778);

